# Generated by Django 3.2.5 on 2021-07-16 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_conversationmessage_interview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interview',
            options={},
        ),
        migrations.RemoveField(
            model_name='interview',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='created_by',
        ),
    ]
