# Generated by Django 3.2.5 on 2021-07-16 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20210716_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview',
            old_name='application',
            new_name='app',
        ),
    ]
