# Generated by Django 3.2.5 on 2021-07-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_alter_application_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='changed_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
