# Generated by Django 3.2.5 on 2021-07-15 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_interview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interview',
        ),
    ]
